/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posyandu;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FormLaporan extends javax.swing.JFrame {

    /**
     * Creates new form FormLaporan
     */
    public FormLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        panelLaporan = new javax.swing.JPanel();
        labelLaporan = new javax.swing.JLabel();
        labelNamaAnak = new javax.swing.JLabel();
        labelTB = new javax.swing.JLabel();
        labelBB = new javax.swing.JLabel();
        labelVitamin = new javax.swing.JLabel();
        labelImunisasi = new javax.swing.JLabel();
        fieldNamaAnak = new javax.swing.JTextField();
        fieldTB = new javax.swing.JTextField();
        fieldBB = new javax.swing.JTextField();
        fieldVitamin = new javax.swing.JTextField();
        fieldImunisasi = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        panelHeader = new javax.swing.JPanel();
        buttonExit = new javax.swing.JButton();
        buttonLogin = new javax.swing.JButton();
        buttonData = new javax.swing.JButton();
        buttonLaporan1 = new javax.swing.JButton();

        jTextField2.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Posyandu - Kelurahan Kuin Utara");

        jPanel1.setBackground(new java.awt.Color(43, 138, 216));

        panelLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelLaporan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelLaporan.setText("Laporan ");

        labelNamaAnak.setText("Nama Anak");

        labelTB.setText("Tinggi Badan");

        labelBB.setText("Berat Badan");

        labelVitamin.setText("Vitamin");

        labelImunisasi.setText("Imunisasi");

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLaporanLayout = new javax.swing.GroupLayout(panelLaporan);
        panelLaporan.setLayout(panelLaporanLayout);
        panelLaporanLayout.setHorizontalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLaporanLayout.createSequentialGroup()
                        .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelLaporan)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLaporanLayout.createSequentialGroup()
                        .addGroup(panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNamaAnak)
                            .addComponent(labelTB)
                            .addComponent(labelBB)
                            .addComponent(labelVitamin)
                            .addComponent(labelImunisasi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldNamaAnak, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(fieldTB)
                            .addComponent(fieldBB)
                            .addComponent(fieldVitamin)
                            .addComponent(fieldImunisasi))
                        .addGap(8, 8, 8)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelLaporanLayout.setVerticalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLaporan)
                .addGap(18, 18, 18)
                .addGroup(panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaAnak)
                    .addComponent(fieldNamaAnak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTB)
                    .addComponent(fieldTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBB)
                    .addComponent(fieldBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVitamin)
                    .addComponent(fieldVitamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelImunisasi)
                    .addComponent(fieldImunisasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonHapus))
                .addContainerGap())
        );

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Adi", "60", "14", "Vitamin B", "Campak Rubella"},
                {"Dina", "50", "15", "Vitamin C", "BCG"},
                {"Anya", "62", "12", "Vitamin A", "Hepatitis B"}
            },
            new String [] {
                "Nama Anak", "Tinggi Badan", "Berat Badan", "Vitamin", "Imunisasi"
            }
        ));
        jScrollPane1.setViewportView(tabelData);

        panelHeader.setBackground(new java.awt.Color(255, 167, 53));

        buttonExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        buttonLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        buttonData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonData.setText("Data");
        buttonData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataActionPerformed(evt);
            }
        });

        buttonLaporan1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonLaporan1.setText("Laporan");
        buttonLaporan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLaporan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonLaporan1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExit)
                    .addComponent(buttonLogin)
                    .addComponent(buttonData)
                    .addComponent(buttonLaporan1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        inputDataTabel();
    }//GEN-LAST:event_buttonSimpanActionPerformed
    
    // method procedure
    private void inputDataTabel() {
        DefaultTableModel dataModel = (DefaultTableModel) tabelData.getModel();
        List list = new ArrayList<>();
        tabelData.setAutoCreateColumnsFromModel(true);
        if(fieldNamaAnak.getText().equals("")) {
           JOptionPane.showMessageDialog(null, "Nama anak tidak boleh kosong");
        } else if(fieldTB.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tinggi badan tidak boleh kosong");
        } else if(fieldBB.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Berat badan tidak boleh kosong");
        } else if(fieldVitamin.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vitamin tidak boleh kosong");
        } else {
            list.add(fieldNamaAnak.getText());
            list.add(fieldTB.getText());
            list.add(fieldBB.getText());
            list.add(fieldVitamin.getText());
            list.add(fieldImunisasi.getText());
            dataModel.addRow(list.toArray());
        }
    }
    
    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) tabelData.getModel();
        // percabangan
        int n = JOptionPane.showConfirmDialog(
            null,
            "Apakah Anda yakin ingin menghapus data?",
            "Hapus Data",
            JOptionPane.YES_NO_OPTION);

        if(n == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Data anda telah dihapus");
            if(tabelData.getRowCount() > 0) {
            // perulangan
            for(int i = tabelData.getRowCount() - 1; i > -1; i--) {
                dataModel.removeRow(i);
            }
          }
        } else if(n == JOptionPane.NO_OPTION) {}
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        String setPassword = JOptionPane.showInputDialog("Masukkan password untuk keluar");
        
        if(setPassword.equals("admin")) {
           new FormAwal().setVisible(true);
           dispose();
        } else {
           String setPasswordLoop = JOptionPane.showInputDialog("Password yang Anda masukkan salah. Silakan coba lagi");
           while(!(setPasswordLoop.equals("admin"))) {
                JOptionPane.showInputDialog("Password yang Anda masukkan salah. Silakan coba lagi");
                break;
           }
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataActionPerformed
        // TODO add your handling code here:
        new FormData().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonDataActionPerformed

    private void buttonLaporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLaporan1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Anda berada di halaman Laporan");
    }//GEN-LAST:event_buttonLaporan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonData;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonLaporan;
    private javax.swing.JButton buttonLaporan1;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JTextField fieldBB;
    private javax.swing.JTextField fieldImunisasi;
    private javax.swing.JTextField fieldNamaAnak;
    private javax.swing.JTextField fieldTB;
    private javax.swing.JTextField fieldVitamin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelBB;
    private javax.swing.JLabel labelImunisasi;
    private javax.swing.JLabel labelLaporan;
    private javax.swing.JLabel labelNamaAnak;
    private javax.swing.JLabel labelTB;
    private javax.swing.JLabel labelVitamin;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLaporan;
    private javax.swing.JTable tabelData;
    // End of variables declaration//GEN-END:variables
}
