/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posyandu;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FormData extends javax.swing.JFrame {

    /**
     * Creates new form FormData
     */
    public FormData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroupLP = new javax.swing.ButtonGroup();
        panelBody = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        buttonExit = new javax.swing.JButton();
        buttonLogin = new javax.swing.JButton();
        buttonData = new javax.swing.JButton();
        buttonLaporan = new javax.swing.JButton();
        panelDataAnak = new javax.swing.JPanel();
        labelDataAnak = new javax.swing.JLabel();
        labelNamaAnak = new javax.swing.JLabel();
        labelJK = new javax.swing.JLabel();
        labelUsia = new javax.swing.JLabel();
        labelNamaIbu = new javax.swing.JLabel();
        labelTL = new javax.swing.JLabel();
        fieldNamaAnak = new javax.swing.JTextField();
        radioL = new javax.swing.JRadioButton();
        radioP = new javax.swing.JRadioButton();
        buttonSimpan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        fieldUsia = new javax.swing.JTextField();
        fieldNamaIbu = new javax.swing.JTextField();
        fieldTL = new javax.swing.JTextField();
        labelAlamat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaAlamat = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Posyandu - Kelurahan Kuin Utara");

        panelBody.setBackground(new java.awt.Color(43, 138, 216));

        panelHeader.setBackground(new java.awt.Color(255, 167, 53));

        buttonExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        buttonLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        buttonData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonData.setText("Data");
        buttonData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataActionPerformed(evt);
            }
        });

        buttonLaporan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonLaporan.setText("Laporan");
        buttonLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonLaporan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExit)
                    .addComponent(buttonLogin)
                    .addComponent(buttonData)
                    .addComponent(buttonLaporan))
                .addContainerGap())
        );

        labelDataAnak.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDataAnak.setText("Data Anak");

        labelNamaAnak.setText("Nama Anak");

        labelJK.setText("Jenis Kelamin");

        labelUsia.setText("Usia");

        labelNamaIbu.setText("Nama Ibu");

        labelTL.setText("Tanggal Lahir");

        fieldNamaAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaAnakActionPerformed(evt);
            }
        });

        buttonGroupLP.add(radioL);
        radioL.setText("Laki-Laki");
        radioL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLActionPerformed(evt);
            }
        });

        buttonGroupLP.add(radioP);
        radioP.setText("Perempuan");
        radioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPActionPerformed(evt);
            }
        });

        buttonSimpan.setText("Simpan");
        buttonSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSimpanMouseClicked(evt);
            }
        });
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        fieldUsia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsiaActionPerformed(evt);
            }
        });

        fieldNamaIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaIbuActionPerformed(evt);
            }
        });

        fieldTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTLActionPerformed(evt);
            }
        });

        labelAlamat.setText("Alamat");

        txtAreaAlamat.setColumns(20);
        txtAreaAlamat.setRows(5);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtAreaAlamat, org.jdesktop.beansbinding.ELProperty.create("TRUE"), txtAreaAlamat, org.jdesktop.beansbinding.BeanProperty.create("lineWrap"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(txtAreaAlamat);

        javax.swing.GroupLayout panelDataAnakLayout = new javax.swing.GroupLayout(panelDataAnak);
        panelDataAnak.setLayout(panelDataAnakLayout);
        panelDataAnakLayout.setHorizontalGroup(
            panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataAnakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataAnakLayout.createSequentialGroup()
                        .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelJK)
                            .addComponent(labelNamaIbu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataAnakLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(fieldNamaIbu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDataAnakLayout.createSequentialGroup()
                                .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioP)
                                    .addComponent(radioL))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelDataAnakLayout.createSequentialGroup()
                        .addComponent(labelNamaAnak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldNamaAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDataAnakLayout.createSequentialGroup()
                        .addComponent(labelUsia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldUsia, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDataAnakLayout.createSequentialGroup()
                        .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDataAnakLayout.createSequentialGroup()
                                .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelDataAnak))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataAnakLayout.createSequentialGroup()
                        .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTL)
                            .addComponent(labelAlamat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(fieldTL, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelDataAnakLayout.setVerticalGroup(
            panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataAnakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDataAnak)
                .addGap(24, 24, 24)
                .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaAnak)
                    .addComponent(fieldNamaAnak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJK)
                    .addComponent(radioL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioP)
                .addGap(11, 11, 11)
                .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsia)
                    .addComponent(fieldUsia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaIbu)
                    .addComponent(fieldNamaIbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTL)
                    .addComponent(fieldTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlamat)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonHapus))
                .addContainerGap())
        );

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Adi", "Laki-Laki",  new Integer(3), "Bunti", "4-05-19", "Jl. Surajaya No.46"},
                {"Dina", "Perempuan",  new Integer(2), "Mia", "2-10-20", "Jl. Sukabunga No.9"},
                {"Anya", "Perempuan",  new Integer(2), "Yor", "17-11-20", "Jl. Anime Sejahtera"}
            },
            new String [] {
                "Nama Anak", "Jenis Kelamin", "Usia", "Nama Ibu", "Tanggal Lahir", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelData);

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDataAnak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDataAnak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void fieldNamaAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaAnakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaAnakActionPerformed

    private void fieldUsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsiaActionPerformed

    private void fieldNamaIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaIbuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaIbuActionPerformed

    private void fieldTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTLActionPerformed
    
    String jk = "";
    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        radioButtonSelected();
        inputDataTabel();
    }//GEN-LAST:event_buttonSimpanActionPerformed
    
    // method procedure
    private void inputDataTabel() {
        DefaultTableModel dataModel = (DefaultTableModel) tabelData.getModel();
        List list = new ArrayList<>();
        tabelData.setAutoCreateColumnsFromModel(true);
        
        // validasi input
        if(fieldNamaAnak.getText().equals("")) {
           JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong");
        } else if(jk.equals("")) {
           JOptionPane.showMessageDialog(null, "Jenis kelamin harus dipilih");
        } else if(fieldUsia.getText().equals("")) {
           JOptionPane.showMessageDialog(null, "Usia tidak boleh kosong");
        } else if(fieldNamaIbu.getText().equals("")) {
           JOptionPane.showMessageDialog(null, "Nama Ibu tidak boleh kosong");
        } else if(fieldTL.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tanggal Lahir tidak boleh kosong");
        } else if(txtAreaAlamat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong");
        } else {
            list.add(fieldNamaAnak.getText());
            list.add(jk);
            list.add(fieldUsia.getText());
            list.add(fieldNamaIbu.getText());
            list.add(fieldTL.getText());
            list.add(txtAreaAlamat.getText());
            dataModel.addRow(list.toArray());
        }
    }
    
    // method function
    private String radioButtonSelected() {
        if(radioL.isSelected()) {
            jk = radioL.getText();
        } else {
            jk = radioP.getText();
        }
        return jk;
    }
    
    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) tabelData.getModel();
        // percabangan
        int n = JOptionPane.showConfirmDialog(
            null,
            "Apakah Anda yakin ingin menghapus data?",
            "Hapus Data",
            JOptionPane.YES_NO_OPTION);

        if(n == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Data anda telah dihapus");
            if(tabelData.getRowCount() > 0) {
            // perulangan
            for(int i = tabelData.getRowCount() - 1; i > -1; i--) {
                dataModel.removeRow(i);
            }
          }
        } else if(n == JOptionPane.NO_OPTION) {}
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLaporanActionPerformed
        // TODO add your handling code here:
        new FormLaporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonLaporanActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        String setPassword = JOptionPane.showInputDialog("Masukkan password untuk keluar");
        
        if(setPassword.equals("admin")) {
           new FormAwal().setVisible(true);
           dispose();
        } else {
           String setPasswordLoop = JOptionPane.showInputDialog("Password yang Anda masukkan salah. Silakan coba lagi");
           
           while(!(setPasswordLoop.equals("admin"))) {
                JOptionPane.showInputDialog("Password yang Anda masukkan salah. Silakan coba lagi");
                break;
           }
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Anda berada di halaman Data");
    }//GEN-LAST:event_buttonDataActionPerformed

    private void radioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPActionPerformed

    private void radioLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLActionPerformed

    private void buttonSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSimpanMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_buttonSimpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonData;
    private javax.swing.JButton buttonExit;
    private javax.swing.ButtonGroup buttonGroupLP;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonLaporan;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JTextField fieldNamaAnak;
    private javax.swing.JTextField fieldNamaIbu;
    private javax.swing.JTextField fieldTL;
    private javax.swing.JTextField fieldUsia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelDataAnak;
    private javax.swing.JLabel labelJK;
    private javax.swing.JLabel labelNamaAnak;
    private javax.swing.JLabel labelNamaIbu;
    private javax.swing.JLabel labelTL;
    private javax.swing.JLabel labelUsia;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelDataAnak;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JRadioButton radioL;
    private javax.swing.JRadioButton radioP;
    private javax.swing.JTable tabelData;
    private javax.swing.JTextArea txtAreaAlamat;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
