/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class Praktikum56No2 extends javax.swing.JFrame {

    /**
     * Creates new form Praktikum56No2
     */
    public Praktikum56No2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInputTanggal = new javax.swing.JLabel();
        labelInputBulan = new javax.swing.JLabel();
        fieldTanggal = new javax.swing.JTextField();
        fieldBulan = new javax.swing.JTextField();
        buttonProses = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        labelZodiak = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelInputTanggal.setText("Input Tanggal ");

        labelInputBulan.setText("Input Bulan");

        fieldTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTanggalActionPerformed(evt);
            }
        });

        buttonProses.setText("proses");
        buttonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesActionPerformed(evt);
            }
        });

        buttonReset.setText("reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        labelZodiak.setText("Zodiak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelInputBulan)
                                    .addComponent(labelInputTanggal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldTanggal)
                                    .addComponent(fieldBulan, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(buttonProses)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonReset))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(labelZodiak)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInputTanggal)
                    .addComponent(fieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInputBulan)
                    .addComponent(fieldBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonProses)
                    .addComponent(buttonReset))
                .addGap(18, 18, 18)
                .addComponent(labelZodiak)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTanggalActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_fieldTanggalActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        fieldBulan.setText("");
        fieldTanggal.setText("");
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesActionPerformed
        // TODO add your handling code here:
        int tanggal = Integer.parseInt(fieldTanggal.getText());
        String bulan = fieldBulan.getText();
        
        if((tanggal >= 20 && tanggal <= 31 && bulan.equalsIgnoreCase("Januari")) || (tanggal >= 1 && tanggal <= 18 && bulan.equalsIgnoreCase("Februari"))) {
            labelZodiak.setText("Aquarius");
        } else if((tanggal >= 19 && tanggal <= 28 && bulan.equalsIgnoreCase("Februari")) || (tanggal >= 1 && tanggal <= 20 && bulan.equalsIgnoreCase("Maret"))) {
            labelZodiak.setText("Pisces");
        } else if((tanggal >= 21 && tanggal <= 31 && bulan.equalsIgnoreCase("Maret")) || (tanggal >= 1 && tanggal <= 20 && bulan.equalsIgnoreCase("April"))) {
            labelZodiak.setText("Aries");
        } else if((tanggal >= 21 && tanggal <= 30 && bulan.equalsIgnoreCase("April")) || (tanggal >= 1 && tanggal <= 20 && bulan.equalsIgnoreCase("Mei"))) {
            labelZodiak.setText("Taurus");
        } else if((tanggal >= 21 && tanggal <= 31 && bulan.equalsIgnoreCase("Mei")) || (tanggal >= 1 && tanggal <= 20 && bulan.equalsIgnoreCase("Juni"))) {
            labelZodiak.setText("Gemini");
        } else if((tanggal >= 21 && tanggal <= 30 && bulan.equalsIgnoreCase("Juni")) || (tanggal >= 1 && tanggal <= 20 && bulan.equalsIgnoreCase("Juli"))) {
            labelZodiak.setText("Cancer");
        } else if((tanggal >= 21 && tanggal <= 31 && bulan.equalsIgnoreCase("Juli")) || (tanggal >= 1 && tanggal <= 21 && bulan.equalsIgnoreCase("Agustus"))) {
            labelZodiak.setText("Leo");
        } else if((tanggal >= 22 && tanggal <= 31 && bulan.equalsIgnoreCase("Agustus")) || (tanggal >= 1 && tanggal <= 22 && bulan.equalsIgnoreCase("September"))) {
            labelZodiak.setText("Virgo");
        } else if((tanggal >= 23 && tanggal <= 30 && bulan.equalsIgnoreCase("September")) || (tanggal >= 1 && tanggal <= 22 && bulan.equalsIgnoreCase("Oktober"))) {
            labelZodiak.setText("Libra");
        } else if((tanggal >= 23 && tanggal <= 31 && bulan.equalsIgnoreCase("Oktober")) || (tanggal >= 1 && tanggal <= 22 && bulan.equalsIgnoreCase("November"))) {
            labelZodiak.setText("Scorpio");
        } else if((tanggal >= 23 && tanggal <= 30 && bulan.equalsIgnoreCase("November")) || (tanggal >= 1 && tanggal <= 20 && bulan.equalsIgnoreCase("Desember"))) {
            labelZodiak.setText("Sagitarius");
        } else if((tanggal >= 21 && tanggal <= 31 && bulan.equalsIgnoreCase("Desember")) || (tanggal >= 1 && tanggal <= 19 && bulan.equalsIgnoreCase("Januari"))) {
            labelZodiak.setText("Capricorn");
        } else {
            labelZodiak.setText("Input yang Anda masukkan salah!");
        }
    }//GEN-LAST:event_buttonProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktikum56No2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktikum56No2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktikum56No2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktikum56No2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktikum56No2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProses;
    private javax.swing.JButton buttonReset;
    private javax.swing.JTextField fieldBulan;
    private javax.swing.JTextField fieldTanggal;
    private javax.swing.JLabel labelInputBulan;
    private javax.swing.JLabel labelInputTanggal;
    private javax.swing.JLabel labelZodiak;
    // End of variables declaration//GEN-END:variables
}
